# Ubuntu 24.04 + HotPocket

FROM ubuntu:noble

COPY libblake3.so /usr/local/lib/
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        sqlite3 \
        fuse3 \
        openssl \
        ca-certificates \
        curl \
        && curl -O http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb \
        && dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /usr/local/bin/hotpocket

COPY hpcore hpfs hpws evernode-license.pdf /usr/local/bin/hotpocket/

ENTRYPOINT ["/usr/local/bin/hotpocket/hpcore"]
