# HotPocket (Ubuntu 20.04) + NodeJs 14.x

FROM hotpocketdev/hotpocket:ubt.20.04

RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs