# Ubuntu 20.04 + HotPocket

FROM ubuntu:focal

COPY libblake3.so /usr/local/lib/
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        libssl1.1 \
        sqlite3 \
        fuse3 \
        openssl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /usr/local/bin/hotpocket

COPY hpcore hpfs hpws hpsh /usr/local/bin/hotpocket/

ENTRYPOINT ["/usr/local/bin/hotpocket/hpcore"]
