# Ubuntu 20.04 + HotPocket

FROM ubuntu:focal

COPY libblake3.so /usr/local/lib/
RUN apt-get update && apt-get install -y \
    libssl1.1 \
    sqlite3 \
    fuse3
    
RUN mkdir /usr/local/bin/hotpocket
COPY hpcore hpfs hpws appbill /usr/local/bin/hotpocket/

ENTRYPOINT ["/usr/local/bin/hotpocket/hpcore"]
