# Ubuntu 20.04 + HotPocket

FROM ubuntu:focal

RUN apt-get update
RUN apt-get install -y libssl1.1 sqlite3

# Install shared libraries.
# Copy shared libraries and register it.
COPY ./libfuse3.so.3 /usr/local/lib/
COPY ./libblake3.so /usr/local/lib/
RUN ldconfig
COPY ./fusermount3 /usr/local/bin/

# hpcore binary is copied to /hp directory withtin the docker image.
WORKDIR /hp
COPY ./hpcore .
COPY ./hpfs .
COPY ./hpws .

ENTRYPOINT ["/hp/hpcore"]
